# Generated by Django 4.2.1 on 2023-05-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nessal_app', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
